/* tslint:disable */
/* eslint-disable */
/**
 * News Hook API
 * API for monitoring and alerting on news and content updates
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserDocumentItem } from './UserDocumentItem';
import {
    UserDocumentItemFromJSON,
    UserDocumentItemFromJSONTyped,
    UserDocumentItemToJSON,
    UserDocumentItemToJSONTyped,
} from './UserDocumentItem';

/**
 * 
 * @export
 * @interface UserDocumentListResponse
 */
export interface UserDocumentListResponse {
    /**
     * 
     * @type {Array<UserDocumentItem>}
     * @memberof UserDocumentListResponse
     */
    documents: Array<UserDocumentItem>;
    /**
     * 
     * @type {number}
     * @memberof UserDocumentListResponse
     */
    totalCount: number;
}

/**
 * Check if a given object implements the UserDocumentListResponse interface.
 */
export function instanceOfUserDocumentListResponse(value: object): value is UserDocumentListResponse {
    if (!('documents' in value) || value['documents'] === undefined) return false;
    if (!('totalCount' in value) || value['totalCount'] === undefined) return false;
    return true;
}

export function UserDocumentListResponseFromJSON(json: any): UserDocumentListResponse {
    return UserDocumentListResponseFromJSONTyped(json, false);
}

export function UserDocumentListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserDocumentListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'documents': ((json['documents'] as Array<any>).map(UserDocumentItemFromJSON)),
        'totalCount': json['total_count'],
    };
}

export function UserDocumentListResponseToJSON(json: any): UserDocumentListResponse {
    return UserDocumentListResponseToJSONTyped(json, false);
}

export function UserDocumentListResponseToJSONTyped(value?: UserDocumentListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'documents': ((value['documents'] as Array<any>).map(UserDocumentItemToJSON)),
        'total_count': value['totalCount'],
    };
}

